## Exercício 1: Vestibular

Considere que a os dados gerados na célula abaixo contêm o número de acertos de 100 alunos em um vestibular para um curso de exatas, divididas pelos respectivos assuntos. Considere que cada assunto possui um número de questões conforme a tabela abaixo:

| assunto | número de questões |
|:---:|:---:|
| Matemática | 24 |
| Português | 18 |
| Geografia | 8 |
| Inglês | 8 |
| História | 8 |
| Física | 12 |
| Química | 12 |

Usando os comandos de operações com DataFrames que você aprendeu na Aula 03, calcule:

1. (operações com escalar) Calcule o percentual de acerto dos alunos por assunto.  
2. (operações entre *DataFrames) Calcule o total de acertos de cada aluno.  
3. Calcule o porcentual geral de cada aluno.  
4. Suponha que a nota de corte para a segunda fase seja 45. Quantos alunos tiveram nota maior que 45?

In [320]:
import pandas as pd
import numpy as np

np.random.seed(42)

df_mat = pd.DataFrame(np.random.randint(24, size=(101, 1)), columns=['Qt_acertos'])

df_por = pd.DataFrame(np.random.randint(18, size=(101, 1)), columns=['Qt_acertos'])

df_geo = pd.DataFrame(np.random.randint(8, size=(101, 1)), columns=['Qt_acertos'])

df_ing = pd.DataFrame(np.random.randint(8, size=(101, 1)), columns=['Qt_acertos'])

df_his = pd.DataFrame(np.random.randint(8, size=(101, 1)), columns=['Qt_acertos'])

df_fis = pd.DataFrame(np.random.randint(12, size=(101, 1)), columns=['Qt_acertos'])

df_qui = pd.DataFrame(np.random.randint(12, size=(101, 1)), columns=['Qt_acertos'])

In [321]:
# 1) Seu código aqui

alunos = []

frame = pd.DataFrame(alunos, columns=['mat', 'por', 'geo', 'ing', 'his', 'fis', 'qui'], index=range(1,101))

# preenchendo a tabela

frame['mat'] = df_mat
frame['por'] = df_por
frame['geo'] = df_geo
frame['ing'] = df_ing
frame['his'] = df_his
frame['fis'] = df_fis
frame['qui'] = df_qui

# percentual de acerto por disciplina

frame['perc_mat'] = round(df_mat / 24, 2)
frame['perc_por'] = round(df_por / 18, 2)
frame['perc_geo'] = round(df_geo / 8, 2)
frame['perc_ing'] = round(df_ing / 8, 2)
frame['perc_his'] = round(df_his / 8, 2)
frame['perc_fis'] = round(df_fis / 12, 2)
frame['perc_qui'] = round(df_qui / 12, 2)

frame.head()

,mat,por,geo,ing,his,fis,qui,perc_mat,perc_por,perc_geo,perc_ing,perc_his,perc_fis,perc_qui
1,19,16,3,7,2,9,4,0.79,0.89,0.38,0.88,0.25,0.75,0.33
2,14,7,2,3,5,0,8,0.58,0.39,0.25,0.38,0.62,0.00,0.67
3,10,2,5,7,7,1,7,0.42,0.11,0.62,0.88,0.88,0.08,0.58
4,7,2,7,7,6,5,2,0.29,0.11,0.88,0.88,0.75,0.42,0.17
5,20,0,4,7,4,8,0,0.83,0.00,0.50,0.88,0.50,0.67,0.00

In [322]:
# 2) total de acertos da prova

frame['total_acertos'] = df_mat + df_por + df_geo + df_ing + df_his + df_fis + df_qui

frame.head()

,mat,por,geo,ing,his,fis,qui,perc_mat,perc_por,perc_geo,perc_ing,perc_his,perc_fis,perc_qui,total_acertos
1,19,16,3,7,2,9,4,0.79,0.89,0.38,0.88,0.25,0.75,0.33,60
2,14,7,2,3,5,0,8,0.58,0.39,0.25,0.38,0.62,0.00,0.67,39
3,10,2,5,7,7,1,7,0.42,0.11,0.62,0.88,0.88,0.08,0.58,39
4,7,2,7,7,6,5,2,0.29,0.11,0.88,0.88,0.75,0.42,0.17,36
5,20,0,4,7,4,8,0,0.83,0.00,0.50,0.88,0.50,0.67,0.00,43

In [323]:
# 3) percentual da prova => nota máxima = 90

frame['perc_prova'] = round(frame['total_acertos'] / 90, 2)

frame.head()

,mat,por,geo,ing,his,fis,qui,perc_mat,perc_por,perc_geo,perc_ing,perc_his,perc_fis,perc_qui,total_acertos,perc_prova
1,19,16,3,7,2,9,4,0.79,0.89,0.38,0.88,0.25,0.75,0.33,60,0.67
2,14,7,2,3,5,0,8,0.58,0.39,0.25,0.38,0.62,0.00,0.67,39,0.43
3,10,2,5,7,7,1,7,0.42,0.11,0.62,0.88,0.88,0.08,0.58,39,0.43
4,7,2,7,7,6,5,2,0.29,0.11,0.88,0.88,0.75,0.42,0.17,36,0.40
5,20,0,4,7,4,8,0,0.83,0.00,0.50,0.88,0.50,0.67,0.00,43,0.48

In [324]:
# 4) Nota de corte = 45 => quantos alunos foram para 2º fase

frame['fase_2'] = frame['total_acertos'] >= 45

a = frame['fase_2'].sum()

print('Total de alunos na 2ª Fase é', a)

frame.head()

Total de alunos na 2ª Fase é 38

,mat,por,geo,ing,his,fis,qui,perc_mat,perc_por,perc_geo,perc_ing,perc_his,perc_fis,perc_qui,total_acertos,perc_prova,fase_2
1,19,16,3,7,2,9,4,0.79,0.89,0.38,0.88,0.25,0.75,0.33,60,0.67,True
2,14,7,2,3,5,0,8,0.58,0.39,0.25,0.38,0.62,0.00,0.67,39,0.43,False
3,10,2,5,7,7,1,7,0.42,0.11,0.62,0.88,0.88,0.08,0.58,39,0.43,False
4,7,2,7,7,6,5,2,0.29,0.11,0.88,0.88,0.75,0.42,0.17,36,0.40,False
5,20,0,4,7,4,8,0,0.83,0.00,0.50,0.88,0.50,0.67,0.00,43,0.48,False

## 2) Vestibular II

Ainda sobre o mesmo banco de dados:

1. Neste vestibular, quem 'zera' em matemática, física ou química está desqualificado. Monte um novo *DataFrame* com os alunos desqualificados por este critério.
2. Quantos são esses alunos?
3. Qual a média desses alunos em história e geografia?
4. Monte um *DataFrame* com os alunos que passaram para a segunda fase. Repare que estes alunos não podem ter sido desqualificados.

In [325]:
# Novo DataFrame ==> frame2

alunos = []

frame2 = pd.DataFrame(alunos, columns=['mat', 'por', 'geo', 'ing', 'his', 'fis', 'qui'], index=range(1,101))

# preenchendo a tabela

frame2['mat'] = df_mat
frame2['por'] = df_por
frame2['geo'] = df_geo
frame2['ing'] = df_ing
frame2['his'] = df_his
frame2['fis'] = df_fis
frame2['qui'] = df_qui

frame2['desclassificado'] = frame2['mat'] == 0 
frame2['desclassificado'] = frame2['fis'] == 0
frame2['desclassificado'] = frame2['qui'] == 0

a = frame2['desclassificado'].sum()

print('Total de alunos desclassificados é', a) # resposta do item 2. 

frame2

frame2.loc[frame2['desclassificado']] 

frame3 = frame2.loc[frame2['desclassificado']].copy()

frame3['média_his_geo'] = (frame3['his'] + frame2['geo']) / 2

frame3 # resposta dos itens 1 e 3.

Total de alunos desclassificados é 9

    mat  por  geo  ing  his  fis  qui  desclassificado  média_his_geo
5    20    0    4    7    4    8    0             True            4.0
9    10    8    2    7    2    6    0             True            2.0
15   23    0    2    5    1    9    0             True            1.5
21   11    2    0    5    0    4    0             True            0.0
22    5    0    7    4    7    0    0             True            7.0
28   11    0    2    1    2    4    0             True            2.0
69    3   14    7    4    3    0    0             True            5.0
84   15    4    0    7    7    9    0             True            3.5
87   14    1    7    1    3    2    0             True            5.0

In [326]:
# Frame4 ==> alunos que passaram para 2ª fase

frame4 = frame.loc[frame['fase_2']].copy()

# verificando se o aluno foi desclassificado

frame4['desclassificado'] = frame4['mat'] == 0 
frame4['desclassificado'] = frame4['fis'] == 0
frame4['desclassificado'] = frame4['qui'] == 0

a = frame4['desclassificado'].sum()
b = frame4['fase_2'].sum()

print('Total de alunos desclassificados é', a)
print('Total de alunos na 2ª fase é', b)

# eliminando colunas para reduzir a tabela

del frame4['perc_ing'] 
del frame4['perc_geo']
del frame4['perc_his']

frame4.head()

Total de alunos desclassificados é 0
Total de alunos na 2ª fase é 38

,mat,por,geo,ing,his,fis,qui,perc_mat,perc_por,perc_fis,perc_qui,total_acertos,perc_prova,fase_2,desclassificado
1,19,16,3,7,2,9,4,0.79,0.89,0.75,0.33,60,0.67,True,False
7,18,9,3,2,6,4,3,0.75,0.50,0.33,0.25,45,0.50,True,False
11,23,8,2,7,0,5,7,0.96,0.44,0.42,0.58,52,0.58,True,False
12,20,7,1,3,7,6,6,0.83,0.39,0.50,0.50,50,0.56,True,False
17,21,4,7,5,0,4,6,0.88,0.22,0.33,0.50,47,0.52,True,False

## 3) Vacinações no Acre
Vamos trabalhar agora com a base de vacinações no Acre. Para facilitar a sua vida, copiamos o link do arquivo na célula abaixo.

1. Quantas vacinas estão registradas nessa base?  
2. Quantos pacientes foram vacinados? (considere um paciente para cada valor único de ```paciente_id```)  
3. Quantos pacientes únicos tomaram a primeira dose? OBS: Há um caractere especial neste campo. Receba os valores do campo com o método ```.unique()```.   
4. Quantos pacientes com menos de 18 anos foram vacinados?  
5. Quantos estabelecimentos aplicaram vacina no Acre?


**OBS:** O portal do DATASUS pode apresentar instabilidades, retornando um erro na segunda célula abaixo. Por este motivo está disponível uma base estática, que se for baixada para o seu *working directory* pode ser lida com este comando: ```df = pd.read_csv('registros de vacinacao covid ACRE.csv', sep=';')```.

**OBS2:** Para saber qual é o seu working directory, rode no jupyter: ```!pwd```.

In [327]:
arquivo = 'https://s3-sa-east-1.amazonaws.com/ckan.saude.gov.br/PNI/vacina/uf/2021-05-23/uf%3DAC/part-00000-63e5bee2-3684-4286-b709-7fe85483b04e.c000.csv'

In [328]:
# 1) Sua solução aqui
vacinacao = pd.read_csv('registros de vacinacao covid ACRE.csv', sep=';')
vacinacao.head(5)

,document_id,paciente_id,paciente_idade,paciente_datanascimento,paciente_enumsexobiologico,paciente_racacor_codigo,paciente_racacor_valor,paciente_endereco_coibgemunicipio,paciente_endereco_copais,paciente_endereco_nmmunicipio,...,vacina_lote,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataaplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem,data_importacao_rnds,id_sistema_origem
0,b19cd280-474c-4c22-a35d-8c06bc04a4e0-i0b0,2e091c9a37d3f50d1d705fc80c6448c6fc69b44da9e936...,69,1951-12-28,F,3,PARDA,120050.0,10.0,SENA MADUREIRA,...,210052A,FUNDACAO BUTANTAN,Organization/61189445000156,2021-03-23,1ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-03-25T03:27:19.000Z,NaN
1,a1acc0b6-1cf6-4c4b-adcb-06b473a0faaf-i0b0,f4e17a9e5354cb45e223d85eda02fb2f76048c801675f5...,81,1939-11-22,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,210110,FUNDACAO BUTANTAN,Organization/61189445000156,2021-04-29,2ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-04-30T16:03:14.000Z,NaN
2,af279a98-ba1f-47ea-8214-314a98040b0d-i0b0,6734b26bccf826130ebffa66575977bbe71477b12bcf42...,69,1951-08-14,M,4,AMARELA,120020.0,10.0,CRUZEIRO DO SUL,...,210135,FUNDACAO BUTANTAN,Organization/61189445000156,2021-04-16,1ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-04-16T15:54:39.000Z,NaN
3,4879308e-5050-46bb-b8e2-11fa5646a05c-i0b0,84a341fd350c1ba7117fccbb4d2df417bc0fac0fffac37...,51,1969-12-15,F,3,PARDA,120040.0,10.0,RIO BRANCO,...,202010040,FUNDACAO BUTANTAN,Organization/61189445000156,2021-02-19,2ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-03-10T14:40:54.000Z,NaN
4,000e911b-e3a4-4114-a735-d1f2e6e3797f-i0b0,c59571e19f368d4b0cf08cd3bcabb32e5cd8baad5340f6...,65,1955-11-21,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,212VCD001ZVB,FUNDACAO OSWALDO CRUZ,Organization/33781055000135,2021-03-29,1ª Dose,85,Vacina Covid-19 - Covishield,Novo PNI,2021-04-03T19:44:28.000Z,NaN

In [329]:
vacinacao['vacina_codigo'].unique()

array([86, 85, 89, 87, 88], dtype=int64)

In [330]:
# 1) Quantas vacinas estão registradas nessa base?

v = vacinacao['vacina_codigo'].nunique()

print('A quantidade de vacinas registrada é', v)

A quantidade de vacinas registrada é 5

In [331]:
# 2) Quantos pacientes foram vacinados?

p = vacinacao['paciente_id'].nunique()

print('O total de pacientes vacinados é', p)

O total de pacientes vacinados é 120517

In [332]:
# 3) Quantos pacientes únicos tomaram a primeira dose?

d1 = vacinacao['vacina_descricao_dose'].unique()

#vacinacao['vacina_descricao_dose'].nunique('\xa0\xa0\xa0\xa01ª\xa0Dose')

d1

array(['\xa0\xa0\xa0\xa01ª\xa0Dose', '\xa0\xa0\xa0\xa02ª\xa0Dose',
       '\xa0\xa0\xa0\xa0Dose\xa0'], dtype=object)

In [333]:
# 3) solução alternativa - Quantos pacientes únicos tomaram a primeira dose?

vacinacao['dose1'] = vacinacao['vacina_descricao_dose'] == '\xa0\xa0\xa0\xa01ª\xa0Dose'

d = vacinacao['dose1'].sum()

print('O total de pacientes que tomaram a primeira dose é', d)

O total de pacientes que tomaram a primeira dose é 120939

In [334]:
# 4) Quantos pacientes com menos de 18 anos foram vacinados?

vacinacao['menor_18'] = vacinacao['paciente_idade'] < 18

m = vacinacao['menor_18'].sum()

print('O total de pacientes com menos de 18 anos vacinados é', m)

O total de pacientes com menos de 18 anos vacinados é 55

In [335]:
# 5) Quantos estabelecimentos aplicaram vacina no Acre?

vacinacao['estabelecimento_razaosocial'].nunique()

42

## 4) Vacinação II
Gere um *DataFrame* que contenha somente os estabelecimentos que aplicaram vcinas a menores de 18 anos. Nesse *DataFrame* devem conter somente os dados dos estabelecimentos, mais uma coluna sendo a quantidade de vacinas que o estabelecimento aplicou a menores de 18 anos.  
  
1. crie uma cópia do *DataFrame* original, contendo somente os registros de vacinas realizadas a menores de 18 anos.  
2. crie uma lista das colunas desse *DataFrame* com o atributo de *DataFrame* **.columns()**  
3. Nesse *DataFrame* faça uma contagem do campo ```vacina_categoria_nome```.
3. a partir da lista de colunas, escolha somente aquelas que são referentes ao estabelecimento, faça uma lista com esses valores.  
4. usando o método *.loc*, selecione somente essas variáveis  
5. Aplique o método **.drop_duplicates** e crie uma lista com uma linha para cada estabelecimento, com os dados do estabelecimento

In [336]:
# 1) cópia do DataFrame original - vacinação em menores de 18 anos ==> df

df = vacinacao.loc[vacinacao['menor_18']].copy()

df.head()

,document_id,paciente_id,paciente_idade,paciente_datanascimento,paciente_enumsexobiologico,paciente_racacor_codigo,paciente_racacor_valor,paciente_endereco_coibgemunicipio,paciente_endereco_copais,paciente_endereco_nmmunicipio,...,vacina_fabricante_referencia,vacina_dataaplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem,data_importacao_rnds,id_sistema_origem,dose1,menor_18
1567,fdca313f-b348-422d-94d4-f2c66a87868c-i0b0,f5e6b8c44f7c4d13a87c582def5e8d460435b02f26af8c...,17,2003-07-18,F,4,AMARELA,120025.0,10.0,EPITACIOLANDIA,...,Organization/33781055000135,2021-05-12,1ª Dose,85,Vacina Covid-19 - Covishield,Novo PNI,2021-05-13T16:16:42.000Z,NaN,True,True
6250,b7431955-1faa-4c1e-9246-7c1e7b8bb3cb-i0b0,e1a45c07e3c393d5f0eccf4204a7ceab338f4f06696ecb...,16,2004-05-18,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,Organization/61189445000156,2021-01-29,1ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-02-06T14:02:07.000Z,NaN,True,True
9569,fdb8d3b6-14d9-4bcc-9cfe-acd46b4a317a-i0b0,7cf3b238383a70eeb26841c01817737c9706d5b231e8c2...,17,2004-01-23,F,99,SEM INFORMACAO,120020.0,10.0,CRUZEIRO DO SUL,...,Organization/33781055000135,2021-05-15,1ª Dose,85,Vacina Covid-19 - Covishield,Novo PNI,2021-05-18T03:17:02.000Z,NaN,True,True
11338,647e2301-3ba4-463a-8d1e-2b6f38a4d99e-i0b0,53eb7fed5faa26ad17ce21ee378f28e25399ab7e90bc05...,17,2003-05-04,F,4,AMARELA,120030.0,10.0,FEIJO,...,Organization/33781055000135,2021-02-09,1ª Dose,85,Vacina Covid-19 - Covishield,Novo PNI,2021-02-09T22:08:13.000Z,NaN,True,True
15144,7f469e03-bece-49d0-bebc-33ad98e27f54-i0b0,dbaa6420d8a815158387668d0a59a19cf2bb63958e35d1...,16,2004-08-22,F,5,INDIGENA,120035.0,10.0,MARECHAL THAUMATURGO,...,Organization/61189445000156,2021-01-28,1ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-02-09T19:26:03.000Z,NaN,True,True

In [337]:
# 2) crie uma lista das colunas desse DataFrame com o atributo de DataFrame.columns()

df.columns

lista_colunas = df.columns

lista_colunas

Index(['document_id', 'paciente_id', 'paciente_idade',
       'paciente_datanascimento', 'paciente_enumsexobiologico',
       'paciente_racacor_codigo', 'paciente_racacor_valor',
       'paciente_endereco_coibgemunicipio', 'paciente_endereco_copais',
       'paciente_endereco_nmmunicipio', 'paciente_endereco_nmpais',
       'paciente_endereco_uf', 'paciente_endereco_cep',
       'paciente_nacionalidade_enumnacionalidade', 'estabelecimento_valor',
       'estabelecimento_razaosocial', 'estalecimento_nofantasia',
       'estabelecimento_municipio_codigo', 'estabelecimento_municipio_nome',
       'estabelecimento_uf', 'vacina_grupoatendimento_codigo',
       'vacina_grupoatendimento_nome', 'vacina_categoria_codigo',
       'vacina_categoria_nome', 'vacina_lote', 'vacina_fabricante_nome',
       'vacina_fabricante_referencia', 'vacina_dataaplicacao',
       'vacina_descricao_dose', 'vacina_codigo', 'vacina_nome',
       'sistema_origem', 'data_importacao_rnds', 'id_sistema_origem', 'dose1',
       'menor_18'],
      dtype='object')

In [338]:
# 3) Nesse DataFrame faça uma contagem do campo vacina_categoria_nome

df['vacina_categoria_nome'].nunique()

5

In [339]:
# 4) a partir da lista de colunas ==> selecione colunas referentes ao estabelecimento

lista_estab = lista_colunas[lista_colunas.str.contains('estab')]

lista_estab

Index(['estabelecimento_valor', 'estabelecimento_razaosocial',
       'estabelecimento_municipio_codigo', 'estabelecimento_municipio_nome',
       'estabelecimento_uf'],
      dtype='object')

In [340]:
# 5) usando o método .loc, selecione somente essas variáveis

df.loc[:,lista_estab].head()

,estabelecimento_valor,estabelecimento_razaosocial,estabelecimento_municipio_codigo,estabelecimento_municipio_nome,estabelecimento_uf
1567,2001314,PREFEITURA MUNICIPAL DE EPITACIOLANDIA,120025,EPITACIOLANDIA,AC
6250,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,120040,RIO BRANCO,AC
9569,6159087,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,120020,CRUZEIRO DO SUL,AC
11338,2000040,PREFEITURA MUNICIPAL DE FEIJO,120030,FEIJO,AC
15144,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,120035,MARECHAL THAUMATURGO,AC

In [341]:
# 6) Aplique o método .drop_duplicates e crie uma lista com uma linha para cada estabelecimento, com os dados do estabelecimento

df.loc[:,lista_estab].drop_duplicates()
df.loc[:,lista_estab]
df['estabelecimento_razaosocial'].unique()

array(['PREFEITURA MUNICIPAL DE EPITACIOLANDIA',
       'PREFEITURA MUNICIPAL DE RIO BRANCO',
       'PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL',
       'PREFEITURA MUNICIPAL DE FEIJO',
       'DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO JURUA',
       'PREFEITURA MUNICIPAL DE PORTO WALTER',
       'PREFEITURA MUNICIPAL DE ASSIS BRASIL',
       'PREFEITURA MUNICIPAL DE TARAUACA',
       'DISTRITO SANITARIO ESPECIAL DE SAUDE INDIGENA ALTO RIO PURUS',
       'DISTRITO SANITARIO ESPECIAL INDIGENA ALTO JURUA',
       'SECRETARIA DE ESTADO DE SAUDE DO ACRE', 'MINISTERIO DA SAUDE',
       'PREFEITURA MUNICIPAL DE PORTO ACRE',
       'PREFEITURA MUNICIPAL DE JORDAO'], dtype=object)

In [342]:
# novo DataFrame ==> df1 ==> uma linha para cada estabelecimento, com os dados do estabelecimento

dados_estab = []

df1 = pd.DataFrame(dados_estab, columns=['estabelecimento_valor', 'estabelecimento_municipio_codigo', 'estabelecimento_municipio_nome', 'estabelecimento_uf'], index=df['estabelecimento_razaosocial'].unique())

# preenchendo a tabela df1 - deu ruim

# df1['estabelecimento_valor'] = df.loc[:,lista_estab]['estabelecimento_valor']

df1

,estabelecimento_valor,estabelecimento_municipio_codigo,estabelecimento_municipio_nome,estabelecimento_uf
PREFEITURA MUNICIPAL DE EPITACIOLANDIA,NaN,NaN,NaN,NaN
PREFEITURA MUNICIPAL DE RIO BRANCO,NaN,NaN,NaN,NaN
PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,NaN,NaN,NaN,NaN
PREFEITURA MUNICIPAL DE FEIJO,NaN,NaN,NaN,NaN
DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO JURUA,NaN,NaN,NaN,NaN
PREFEITURA MUNICIPAL DE PORTO WALTER,NaN,NaN,NaN,NaN
PREFEITURA MUNICIPAL DE ASSIS BRASIL,NaN,NaN,NaN,NaN
PREFEITURA MUNICIPAL DE TARAUACA,NaN,NaN,NaN,NaN
DISTRITO SANITARIO ESPECIAL DE SAUDE INDIGENA ALTO RIO PURUS,NaN,NaN,NaN,NaN
DISTRITO SANITARIO ESPECIAL INDIGENA ALTO JURUA,NaN,NaN,NaN,NaN
SECRETARIA DE ESTADO DE SAUDE DO ACRE,NaN,NaN,NaN,NaN
MINISTERIO DA SAUDE,NaN,NaN,NaN,NaN
PREFEITURA MUNICIPAL DE PORTO ACRE,NaN,NaN,NaN,NaN
PREFEITURA MUNICIPAL DE JORDAO,NaN,NaN,NaN,NaN

Caro Tutor, não consegui preencher a tabela acima. Também não sei se era essa a proposta do exercício 6.